/*
 * This file is generated by jOOQ.
*/
package main.java.data;


import javax.annotation.Generated;

import main.java.data.tables.Journals;
import main.java.data.tables.Users;
import main.java.data.tables.records.JournalsRecord;
import main.java.data.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<JournalsRecord, Integer> IDENTITY_JOURNALS = Identities0.IDENTITY_JOURNALS;
    public static final Identity<UsersRecord, Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JournalsRecord> JOURNALS_PKEY = UniqueKeys0.JOURNALS_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<JournalsRecord, UsersRecord> JOURNALS__JOURNALS_USERS_ID_FK = ForeignKeys0.JOURNALS__JOURNALS_USERS_ID_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<JournalsRecord, Integer> IDENTITY_JOURNALS = createIdentity(Journals.JOURNALS, Journals.JOURNALS.ID);
        public static Identity<UsersRecord, Integer> IDENTITY_USERS = createIdentity(Users.USERS, Users.USERS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<JournalsRecord> JOURNALS_PKEY = createUniqueKey(Journals.JOURNALS, "journals_pkey", Journals.JOURNALS.ID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<JournalsRecord, UsersRecord> JOURNALS__JOURNALS_USERS_ID_FK = createForeignKey(main.java.data.Keys.USERS_PKEY, Journals.JOURNALS, "journals__journals_users_id_fk", Journals.JOURNALS.USER_ID);
    }
}
