/*
 * This file is generated by jOOQ.
*/
package xyz.cetacea.data;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;

import xyz.cetacea.data.tables.Groups;
import xyz.cetacea.data.tables.Journals;
import xyz.cetacea.data.tables.UserGroupLinks;
import xyz.cetacea.data.tables.Users;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GROUPS_ID_UINDEX = Indexes0.GROUPS_ID_UINDEX;
    public static final Index GROUPS_PKEY = Indexes0.GROUPS_PKEY;
    public static final Index JOURNALS_PKEY = Indexes0.JOURNALS_PKEY;
    public static final Index USER_GROUP_LINKS_ID_UINDEX = Indexes0.USER_GROUP_LINKS_ID_UINDEX;
    public static final Index USER_GROUP_LINKS_PKEY = Indexes0.USER_GROUP_LINKS_PKEY;
    public static final Index USERS_ID_UINDEX = Indexes0.USERS_ID_UINDEX;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index GROUPS_ID_UINDEX = createIndex("groups_id_uindex", Groups.GROUPS, new OrderField[] { Groups.GROUPS.ID }, true);
        public static Index GROUPS_PKEY = createIndex("groups_pkey", Groups.GROUPS, new OrderField[] { Groups.GROUPS.ID }, true);
        public static Index JOURNALS_PKEY = createIndex("journals_pkey", Journals.JOURNALS, new OrderField[] { Journals.JOURNALS.ID }, true);
        public static Index USER_GROUP_LINKS_ID_UINDEX = createIndex("user_group_links_id_uindex", UserGroupLinks.USER_GROUP_LINKS, new OrderField[] { UserGroupLinks.USER_GROUP_LINKS.ID }, true);
        public static Index USER_GROUP_LINKS_PKEY = createIndex("user_group_links_pkey", UserGroupLinks.USER_GROUP_LINKS, new OrderField[] { UserGroupLinks.USER_GROUP_LINKS.ID }, true);
        public static Index USERS_ID_UINDEX = createIndex("users_id_uindex", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index USERS_PKEY = createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
    }
}
