/*
 * This file is generated by jOOQ.
*/
package xyz.cetacea.data;


import javax.annotation.Generated;

import xyz.cetacea.data.tables.Groups;
import xyz.cetacea.data.tables.Journals;
import xyz.cetacea.data.tables.UserGroupLinks;
import xyz.cetacea.data.tables.Users;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.groups</code>.
     */
    public static final Groups GROUPS = xyz.cetacea.data.tables.Groups.GROUPS;

    /**
     * The table <code>public.journals</code>.
     */
    public static final Journals JOURNALS = xyz.cetacea.data.tables.Journals.JOURNALS;

    /**
     * The table <code>public.user_group_links</code>.
     */
    public static final UserGroupLinks USER_GROUP_LINKS = xyz.cetacea.data.tables.UserGroupLinks.USER_GROUP_LINKS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = xyz.cetacea.data.tables.Users.USERS;
}
