/*
 * This file is generated by jOOQ.
*/
package xyz.cetacea.data.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import xyz.cetacea.data.tables.UserGroupLinks;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupLinksRecord extends UpdatableRecordImpl<UserGroupLinksRecord> implements Record5<Integer, Integer, Integer, Boolean, Timestamp> {

    private static final long serialVersionUID = -1364672836;

    /**
     * Setter for <code>public.user_group_links.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_group_links.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.user_group_links.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_group_links.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.user_group_links.group_id</code>.
     */
    public void setGroupId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_group_links.group_id</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.user_group_links.is_admin</code>.
     */
    public void setIsAdmin(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_group_links.is_admin</code>.
     */
    public Boolean getIsAdmin() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.user_group_links.timestamp_joined</code>.
     */
    public void setTimestampJoined(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_group_links.timestamp_joined</code>.
     */
    public Timestamp getTimestampJoined() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Boolean, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Boolean, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserGroupLinks.USER_GROUP_LINKS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserGroupLinks.USER_GROUP_LINKS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserGroupLinks.USER_GROUP_LINKS.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return UserGroupLinks.USER_GROUP_LINKS.IS_ADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return UserGroupLinks.USER_GROUP_LINKS.TIMESTAMP_JOINED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getIsAdmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getTimestampJoined();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getIsAdmin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getTimestampJoined();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupLinksRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupLinksRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupLinksRecord value3(Integer value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupLinksRecord value4(Boolean value) {
        setIsAdmin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupLinksRecord value5(Timestamp value) {
        setTimestampJoined(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserGroupLinksRecord values(Integer value1, Integer value2, Integer value3, Boolean value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserGroupLinksRecord
     */
    public UserGroupLinksRecord() {
        super(UserGroupLinks.USER_GROUP_LINKS);
    }

    /**
     * Create a detached, initialised UserGroupLinksRecord
     */
    public UserGroupLinksRecord(Integer id, Integer userId, Integer groupId, Boolean isAdmin, Timestamp timestampJoined) {
        super(UserGroupLinks.USER_GROUP_LINKS);

        set(0, id);
        set(1, userId);
        set(2, groupId);
        set(3, isAdmin);
        set(4, timestampJoined);
    }
}
