/*
 * This file is generated by jOOQ.
*/
package xyz.cetacea.data.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Groups implements Serializable {

    private static final long serialVersionUID = -636941458;

    private Integer   id;
    private String    name;
    private String    description;
    private Integer   createdBy;
    private Timestamp timestampCreated;

    public Groups() {}

    public Groups(Groups value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.createdBy = value.createdBy;
        this.timestampCreated = value.timestampCreated;
    }

    public Groups(
        Integer   id,
        String    name,
        String    description,
        Integer   createdBy,
        Timestamp timestampCreated
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.createdBy = createdBy;
        this.timestampCreated = timestampCreated;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getTimestampCreated() {
        return this.timestampCreated;
    }

    public void setTimestampCreated(Timestamp timestampCreated) {
        this.timestampCreated = timestampCreated;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Groups other = (Groups) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!createdBy.equals(other.createdBy))
            return false;
        if (timestampCreated == null) {
            if (other.timestampCreated != null)
                return false;
        }
        else if (!timestampCreated.equals(other.timestampCreated))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.timestampCreated == null) ? 0 : this.timestampCreated.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Groups (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(timestampCreated);

        sb.append(")");
        return sb.toString();
    }
}
