/*
 * This file is generated by jOOQ.
*/
package xyz.cetacea.data.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupLinks implements Serializable {

    private static final long serialVersionUID = 1155871538;

    private Integer   id;
    private Integer   userId;
    private Integer   groupId;
    private Boolean   isAdmin;
    private Timestamp timestampJoined;

    public UserGroupLinks() {}

    public UserGroupLinks(UserGroupLinks value) {
        this.id = value.id;
        this.userId = value.userId;
        this.groupId = value.groupId;
        this.isAdmin = value.isAdmin;
        this.timestampJoined = value.timestampJoined;
    }

    public UserGroupLinks(
        Integer   id,
        Integer   userId,
        Integer   groupId,
        Boolean   isAdmin,
        Timestamp timestampJoined
    ) {
        this.id = id;
        this.userId = userId;
        this.groupId = groupId;
        this.isAdmin = isAdmin;
        this.timestampJoined = timestampJoined;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public Boolean getIsAdmin() {
        return this.isAdmin;
    }

    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    public Timestamp getTimestampJoined() {
        return this.timestampJoined;
    }

    public void setTimestampJoined(Timestamp timestampJoined) {
        this.timestampJoined = timestampJoined;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserGroupLinks (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(groupId);
        sb.append(", ").append(isAdmin);
        sb.append(", ").append(timestampJoined);

        sb.append(")");
        return sb.toString();
    }
}
