/*
 * This file is generated by jOOQ.
*/
package xyz.cetacea.data.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupLinks implements Serializable {

    private static final long serialVersionUID = -1673568816;

    private Integer   id;
    private Integer   userId;
    private Integer   groupId;
    private Boolean   isAdmin;
    private Timestamp timestampJoined;

    public UserGroupLinks() {}

    public UserGroupLinks(UserGroupLinks value) {
        this.id = value.id;
        this.userId = value.userId;
        this.groupId = value.groupId;
        this.isAdmin = value.isAdmin;
        this.timestampJoined = value.timestampJoined;
    }

    public UserGroupLinks(
        Integer   id,
        Integer   userId,
        Integer   groupId,
        Boolean   isAdmin,
        Timestamp timestampJoined
    ) {
        this.id = id;
        this.userId = userId;
        this.groupId = groupId;
        this.isAdmin = isAdmin;
        this.timestampJoined = timestampJoined;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public Boolean getIsAdmin() {
        return this.isAdmin;
    }

    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    public Timestamp getTimestampJoined() {
        return this.timestampJoined;
    }

    public void setTimestampJoined(Timestamp timestampJoined) {
        this.timestampJoined = timestampJoined;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserGroupLinks other = (UserGroupLinks) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (groupId == null) {
            if (other.groupId != null)
                return false;
        }
        else if (!groupId.equals(other.groupId))
            return false;
        if (isAdmin == null) {
            if (other.isAdmin != null)
                return false;
        }
        else if (!isAdmin.equals(other.isAdmin))
            return false;
        if (timestampJoined == null) {
            if (other.timestampJoined != null)
                return false;
        }
        else if (!timestampJoined.equals(other.timestampJoined))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.groupId == null) ? 0 : this.groupId.hashCode());
        result = prime * result + ((this.isAdmin == null) ? 0 : this.isAdmin.hashCode());
        result = prime * result + ((this.timestampJoined == null) ? 0 : this.timestampJoined.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserGroupLinks (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(groupId);
        sb.append(", ").append(isAdmin);
        sb.append(", ").append(timestampJoined);

        sb.append(")");
        return sb.toString();
    }
}
